// Typical US grocery store package sizes for the most common ingredients,
// keyed by the aggregator's normalized key. `pkg` is the package quantity
// expressed in the unit recipes use for that ingredient, `desc` is the
// human label, `perish` is how fast leftovers die (0 = keeps forever,
// 1 = days). Together with the per-recipe need this gives the real waste
// objective: leftoverFraction × perish.
//
// Hand-curated reference (standard US packaging); covers ~87% of shoppable
// ingredient occurrences. Kit-only items (stock concentrates, demi-glace,
// HelloFresh spice blends) are deliberately absent — there is no store
// package to optimize against.

export const storeQuantities = {
  // ── fresh herbs & aromatics (bunch-sized, die fast) ──
  "cilantro": { pkg: 1, unit: "ounce", desc: "1 bunch", perish: 1.0 },
  "chive": { pkg: 0.75, unit: "ounce", desc: "0.75 oz pack", perish: 1.0 },
  "dill": { pkg: 0.75, unit: "ounce", desc: "0.75 oz pack", perish: 1.0 },
  "mint": { pkg: 0.75, unit: "ounce", desc: "0.75 oz pack", perish: 1.0 },
  "tarragon": { pkg: 0.75, unit: "ounce", desc: "0.75 oz pack", perish: 1.0 },
  "sage": { pkg: 0.75, unit: "ounce", desc: "0.75 oz pack", perish: 1.0 },
  "scallion": { pkg: 6, unit: "unit", desc: "1 bunch", perish: 0.9 },
  "ginger": { pkg: 4, unit: "thumb", desc: "1 hand", perish: 0.7 },

  // ── produce ──
  "lemon": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.4 },
  "lime": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.4 },
  "yellow onion": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.2 },
  "red onion": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.2 },
  "shallot": { pkg: 3, unit: "unit", desc: "3-pack", perish: 0.5 },
  "roma tomato": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.7 },
  "tomato": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.7 },
  "zucchini": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.7 },
  "yellow squash": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.7 },
  "carrot": { pkg: 6, unit: "unit", desc: "1 lb bag", perish: 0.5 },
  "shredded carrot": { pkg: 10, unit: "ounce", desc: "10 oz bag", perish: 0.7 },
  "celery": { pkg: 9, unit: "unit", desc: "1 bunch (stalks)", perish: 0.6 },
  "yukon gold potato": { pkg: 24, unit: "ounce", desc: "1.5 lb bag", perish: 0.3 },
  "fingerling potato": { pkg: 24, unit: "ounce", desc: "1.5 lb bag", perish: 0.3 },
  "sweet potato": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.3 },
  "green bean": { pkg: 12, unit: "ounce", desc: "12 oz bag", perish: 0.8 },
  "grape tomato": { pkg: 10, unit: "ounce", desc: "10 oz clamshell", perish: 0.8 },
  "heirloom grape tomato": { pkg: 10, unit: "ounce", desc: "10 oz clamshell", perish: 0.8 },
  "poblano pepper": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.7 },
  "bell pepper": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.6 },
  "red bell pepper": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.6 },
  "green bell pepper": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.6 },
  "long green pepper": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.6 },
  "chili pepper": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.6 },
  "jalapeño": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.6 },
  "mixed green": { pkg: 5, unit: "ounce", desc: "5 oz clamshell", perish: 1.0 },
  "arugula": { pkg: 5, unit: "ounce", desc: "5 oz clamshell", perish: 1.0 },
  "spinach": { pkg: 6, unit: "ounce", desc: "6 oz bag", perish: 0.9 },
  "kale": { pkg: 8, unit: "ounce", desc: "1 bunch", perish: 0.8 },
  "button mushroom": { pkg: 8, unit: "ounce", desc: "8 oz pack", perish: 0.8 },
  "broccoli floret": { pkg: 12, unit: "ounce", desc: "12 oz bag", perish: 0.7 },
  "baby broccoli": { pkg: 8, unit: "ounce", desc: "1 bunch", perish: 0.8 },
  "cauliflower floret": { pkg: 16, unit: "ounce", desc: "16 oz bag", perish: 0.7 },
  "brussel sprout": { pkg: 16, unit: "ounce", desc: "1 lb bag", perish: 0.7 },
  "asparagus": { pkg: 16, unit: "ounce", desc: "1 bunch", perish: 0.8 },
  "avocado": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.8 },
  "cucumber": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.7 },
  "persian cucumber": { pkg: 6, unit: "unit", desc: "6-pack bag", perish: 0.8 },
  "radish": { pkg: 8, unit: "unit", desc: "1 bunch", perish: 0.7 },
  "apple": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.4 },
  "orange": { pkg: 1, unit: "unit", desc: "sold loose", perish: 0.4 },
  "pineapple": { pkg: 16, unit: "ounce", desc: "16 oz chunks", perish: 0.7 },
  "corn": { pkg: 16, unit: "ounce", desc: "16 oz frozen bag", perish: 0.3 },
  "corn on the cob": { pkg: 4, unit: "unit", desc: "4-pack", perish: 0.7 },
  "shredded red cabbage": { pkg: 10, unit: "ounce", desc: "10 oz bag", perish: 0.7 },
  "coleslaw mix": { pkg: 14, unit: "ounce", desc: "14 oz bag", perish: 0.8 },
  "sugar snap pea": { pkg: 8, unit: "ounce", desc: "8 oz bag", perish: 0.8 },
  "pea": { pkg: 16, unit: "ounce", desc: "16 oz frozen bag", perish: 0.2 },

  // ── dairy & eggs ──
  "egg": { pkg: 12, unit: "unit", desc: "1 dozen", perish: 0.3 },
  "milk": { pkg: 64, unit: "ounce", desc: "half gallon", perish: 0.5 },
  "sour cream": { pkg: 32, unit: "tablespoon", desc: "16 oz tub", perish: 0.6 },
  "cream cheese": { pkg: 16, unit: "tablespoon", desc: "8 oz block", perish: 0.5 },
  "ricotta cheese": { pkg: 15, unit: "ounce", desc: "15 oz tub", perish: 0.6 },
  "parmesan cheese": { pkg: 1.25, unit: "cup", desc: "5 oz wedge", perish: 0.4 },
  "monterey jack cheese": { pkg: 2, unit: "cup", desc: "8 oz bag", perish: 0.4 },
  "mozzarella cheese": { pkg: 2, unit: "cup", desc: "8 oz bag", perish: 0.4 },
  "cheddar cheese": { pkg: 2, unit: "cup", desc: "8 oz bag", perish: 0.4 },
  "pepper jack cheese": { pkg: 2, unit: "cup", desc: "8 oz bag", perish: 0.4 },
  "mexican cheese blend": { pkg: 2, unit: "cup", desc: "8 oz bag", perish: 0.4 },
  "italian cheese blend": { pkg: 2, unit: "cup", desc: "8 oz bag", perish: 0.4 },
  "feta cheese": { pkg: 1.5, unit: "cup", desc: "6 oz crumbles", perish: 0.6 },
  "fresh mozzarella": { pkg: 8, unit: "ounce", desc: "8 oz ball", perish: 0.7 },
  "yogurt": { pkg: 1, unit: "unit", desc: "single cup", perish: 0.6 },
  "guacamole": { pkg: 16, unit: "tablespoon", desc: "8 oz tub", perish: 0.8 },

  // ── meat & seafood (mostly bought to size; freezable) ──
  "chicken breast": { pkg: 24, unit: "ounce", desc: "1.5 lb pack", perish: 0.4 },
  "chicken cutlet": { pkg: 20, unit: "ounce", desc: "1.25 lb pack", perish: 0.4 },
  "chicken breast strip": { pkg: 16, unit: "ounce", desc: "1 lb pack", perish: 0.4 },
  "chicken thigh": { pkg: 24, unit: "ounce", desc: "1.5 lb pack", perish: 0.4 },
  "chicken leg": { pkg: 24, unit: "ounce", desc: "1.5 lb pack", perish: 0.4 },
  "ground beef": { pkg: 16, unit: "ounce", desc: "1 lb pack", perish: 0.4 },
  "ground pork": { pkg: 16, unit: "ounce", desc: "1 lb pack", perish: 0.4 },
  "sirloin steak": { pkg: 16, unit: "ounce", desc: "1 lb pack", perish: 0.4 },
  "new york strip steak": { pkg: 12, unit: "ounce", desc: "1 steak", perish: 0.4 },
  "pork chop": { pkg: 16, unit: "ounce", desc: "1 lb pack", perish: 0.4 },
  "pork tenderloin": { pkg: 16, unit: "ounce", desc: "1 lb", perish: 0.4 },
  "italian pork sausage": { pkg: 16, unit: "ounce", desc: "1 lb pack", perish: 0.4 },
  "sweet italian pork sausage": { pkg: 16, unit: "ounce", desc: "1 lb pack", perish: 0.4 },
  "italian chicken sausage": { pkg: 16, unit: "ounce", desc: "1 lb pack", perish: 0.4 },
  "italian chicken sausage mix": { pkg: 16, unit: "ounce", desc: "1 lb pack", perish: 0.4 },
  "bacon": { pkg: 12, unit: "ounce", desc: "12 oz pack", perish: 0.4 },
  "pancetta": { pkg: 4, unit: "ounce", desc: "4 oz pack", perish: 0.5 },
  "shrimp": { pkg: 12, unit: "ounce", desc: "12 oz bag (frozen)", perish: 0.3 },
  "skin-on salmon": { pkg: 12, unit: "ounce", desc: "12 oz fillet", perish: 0.4 },
  "tilapia": { pkg: 12, unit: "ounce", desc: "12 oz fillets", perish: 0.4 },

  // ── bakery ──
  "brioche bun": { pkg: 8, unit: "unit", desc: "8-pack", perish: 0.5 },
  "potato bun": { pkg: 8, unit: "unit", desc: "8-pack", perish: 0.5 },
  "flour tortilla": { pkg: 10, unit: "unit", desc: "10-pack", perish: 0.4 },
  "flatbread": { pkg: 4, unit: "unit", desc: "4-pack", perish: 0.5 },
  "demi-baguette": { pkg: 2, unit: "unit", desc: "2-pack", perish: 0.8 },
  "ciabatta bread": { pkg: 1, unit: "unit", desc: "1 loaf", perish: 0.5 },

  // ── dry goods, canned, jarred (keep nearly forever) ──
  "jasmine rice": { pkg: 4.5, unit: "cup", desc: "2 lb bag", perish: 0 },
  "basmati rice": { pkg: 4.5, unit: "cup", desc: "2 lb bag", perish: 0 },
  "arborio rice": { pkg: 2.25, unit: "cup", desc: "1 lb box", perish: 0 },
  "quinoa": { pkg: 2.5, unit: "cup", desc: "1 lb bag", perish: 0 },
  "farro": { pkg: 2.5, unit: "cup", desc: "1 lb bag", perish: 0 },
  "couscous": { pkg: 2.5, unit: "cup", desc: "1 lb box", perish: 0 },
  "israeli couscous": { pkg: 2.5, unit: "cup", desc: "1 lb box", perish: 0 },
  "panko breadcrumb": { pkg: 4, unit: "cup", desc: "8 oz box", perish: 0.1 },
  "penne pasta": { pkg: 16, unit: "ounce", desc: "1 lb box", perish: 0 },
  "spaghetti": { pkg: 16, unit: "ounce", desc: "1 lb box", perish: 0 },
  "cavatappi pasta": { pkg: 16, unit: "ounce", desc: "1 lb box", perish: 0 },
  "gemelli pasta": { pkg: 16, unit: "ounce", desc: "1 lb box", perish: 0 },
  "orzo pasta": { pkg: 16, unit: "ounce", desc: "1 lb box", perish: 0 },
  "cheese tortelloni": { pkg: 9, unit: "ounce", desc: "9 oz pack", perish: 0.6 },
  "black bean": { pkg: 15.5, unit: "ounce", desc: "1 can", perish: 0.5 },
  "chickpea": { pkg: 15.5, unit: "ounce", desc: "1 can", perish: 0.5 },
  "crushed tomato": { pkg: 1, unit: "box", desc: "1 box", perish: 0.3 },
  "diced tomato": { pkg: 1, unit: "can", desc: "1 can", perish: 0.3 },
  "tomato paste": { pkg: 6, unit: "ounce", desc: "6 oz can", perish: 0.6 },
  "marinara cup": { pkg: 24, unit: "ounce", desc: "24 oz jar", perish: 0.4 },
  "almond": { pkg: 6, unit: "ounce", desc: "6 oz bag", perish: 0.1 },
  "walnut": { pkg: 6, unit: "ounce", desc: "6 oz bag", perish: 0.1 },
  "pecan": { pkg: 6, unit: "ounce", desc: "6 oz bag", perish: 0.1 },
  "peanut": { pkg: 6, unit: "ounce", desc: "6 oz bag", perish: 0.1 },
  "pepita": { pkg: 6, unit: "ounce", desc: "6 oz bag", perish: 0.1 },
  "pine nut": { pkg: 2, unit: "ounce", desc: "2 oz jar", perish: 0.1 },
  "sesame seed": { pkg: 12, unit: "tablespoon", desc: "small jar", perish: 0.1 },
  "dried cranberry": { pkg: 5, unit: "ounce", desc: "5 oz bag", perish: 0.1 },
  "flour": { pkg: 180, unit: "tablespoon", desc: "5 lb bag", perish: 0 },

  // ── condiments & sauces (opened jars keep a while) ──
  "dijon mustard": { pkg: 50, unit: "teaspoon", desc: "9 oz jar", perish: 0.1 },
  "sriracha": { pkg: 96, unit: "teaspoon", desc: "17 oz bottle", perish: 0.05 },
  "hot sauce": { pkg: 30, unit: "teaspoon", desc: "5 oz bottle", perish: 0.05 },
  "hoisin sauce": { pkg: 15, unit: "tablespoon", desc: "8 oz jar", perish: 0.2 },
  "bbq sauce": { pkg: 36, unit: "tablespoon", desc: "18 oz bottle", perish: 0.1 },
  "pesto": { pkg: 6.5, unit: "ounce", desc: "6.5 oz jar", perish: 0.5 },
  "apricot jam": { pkg: 18, unit: "tablespoon", desc: "12 oz jar", perish: 0.1 },
  "fig jam": { pkg: 18, unit: "tablespoon", desc: "12 oz jar", perish: 0.1 },
  "cherry jam": { pkg: 18, unit: "tablespoon", desc: "12 oz jar", perish: 0.1 },
  "maple syrup": { pkg: 24, unit: "tablespoon", desc: "12 oz bottle", perish: 0.05 },
};
